[toolchain]
anchor_version = "0.31.1"
solana_version = "3.0.15"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank_mint = "FjK8AaLTfj8fP8bf88tmwCxu2xyhTXhaSkHGzCEZyczk"
bin_farm = "8FJyoK7UKhYB8qd8187oVWFngQ5ZoVPbNWXSUeZSdgia"
gauge_voter = "DRhe2EXWWPM3G9qRUeGmnVWsV4joxQ5pBw2qXPereQrA"
merkle_distributor = "DWmPoHsRQ4PAff3zY8wuLMpogukmmiCxfFewmB5WQ8kV"
monke_bananas = "myA2F4S7trnQUiksrrB1prR3k95d8znEXZXwHkZw5ZH"
pegged_bridge = "7oHSUPzkPDDtxjXcvjRYKHmSjoBigJ4HUvPRRhf1SCgN"

[programs.mainnet]
bank_mint = "FjK8AaLTfj8fP8bf88tmwCxu2xyhTXhaSkHGzCEZyczk"
bin_farm = "8FJyoK7UKhYB8qd8187oVWFngQ5ZoVPbNWXSUeZSdgia"
gauge_voter = "DRhe2EXWWPM3G9qRUeGmnVWsV4joxQ5pBw2qXPereQrA"
merkle_distributor = "DWmPoHsRQ4PAff3zY8wuLMpogukmmiCxfFewmB5WQ8kV"
monke_bananas = "myA2F4S7trnQUiksrrB1prR3k95d8znEXZXwHkZw5ZH"
pegged_bridge = "7oHSUPzkPDDtxjXcvjRYKHmSjoBigJ4HUvPRRhf1SCgN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
